NewTask/Models/Company.cs
using System;

namespace NewTask.Models
{
    public class Company
    {
        public string CompanyName { get; set; }
        public string Descripton { get; set; }
        public string CompanyAdress { get; set; }
        public DateTime Founded { get; set; }
    }
}

NewTask/Models/Employee.cs
namespace NewTask.Models
{
    public class Employee
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Profession { get; set; }
        public int PhoneNumber { get; set; }
    }
}

NewTask/Models/ErrorViewModel.cs
using System;

namespace NewTask.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NewTask/Models/Partner.cs
namespace NewTask.Models
{
    public class Partner
    {
        public string Name { get; set; }
        public string Adress { get; set; }
    }
}

NewTask/ViewModels/CompanyViewModel.cs
using NewTask.Models;

namespace NewTask.ViewModels
{
    public class CompanyViewModel
    {
        public Company company { get; set; }
        public Partner partner { get; set; }
    }
}

NewTask/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using NewTask.Models;
using NewTask.ViewModels;
using System;

namespace NewTask.Controllers
{
    public class CompanyController : Controller
    {
        public IActionResult Index()
        {
            Company company = new Company()
            {
                CompanyName = "Azersun",
                Descripton = "Description1",
                Founded = DateTime.Now,
                CompanyAdress = "Baku"
            };
            Partner partners = new Partner()
            {
                Name="QarabagFK",
                Adress="Zerbaijan,Agdam"
            };

            CompanyViewModel companyViewModel = new CompanyViewModel()
            {
                company=company,
                partner=partners
            };


            return View(companyViewModel);
        }
    }
}

NewTask/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using NewTask.Models;
using System.Collections.Generic;

namespace NewTask.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Index()
        {
            Employee employee = new Employee()
            {
                Name = "Nadir",
                Surname="Eliyev",
                Profession="Fehle",
                PhoneNumber=7585463

            };
            Employee employee2 = new Employee()
            {
                Name = "Hesen",
                Surname = "Orucov",
                Profession = "Muhendis",
                PhoneNumber = 5216874
            };
            List<Employee> employees = new List<Employee>();
            employees.Add(employee);
            employees.Add(employee2);
            return View(employees);
        }
    }
}

NewTask/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NewTask.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace NewTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NewTask/Views/Company/Index.cshtml
@model CompanyViewModel

<div class="text-center">
    <h1 class="display-4">Company</h1>
    <p> Adi:@Model.company.CompanyName</p>
    <p> Description:@Model.company.Descripton</p>
    <p> Adresi:@Model.company.CompanyAdress</p>
    <p> Yaradildi:@Model.company.Founded</p>
</div>
<hr />

<div class="text-center">
    <h1 class="display-4">Partner</h1>
    <p> Adi:@Model.partner.Name</p>
    <p> Description:@Model.partner.Adress</p>
</div>

NewTask/Views/Employee/Index.cshtml
@model List<Employee>


    @foreach (var employee in Model)
    {
    <div class="text-center">
        <h1 class="display-4">Employee</h1>
        <p> Adi:@employee.Name</p>
        <p> Soyadi:@employee.Surname</p>
        <p> Vezife:@employee.Profession</p>
        <p> Elaqe nomresi:@employee.PhoneNumber</p>
    </div>
}

NewTask/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NewTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NewTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NewTask</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Company" asp-action="Index">Company</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NewTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>